version: "3.9"
services:

  clio:
    container_name: clio_server
    image: clio_server
    # command:
    #   -   /opt/clio/etc/config.json"
    build: clio_docker
    # volumes:
    #   - ./data/clio:/var/log/clio
    networks:
     clio-net:
       ipv4_address: 10.0.0.2

  rippled:
    container_name: rippled
    image: rippled
    build: rippled_docker
    command: test
    environment:
      NETWORK: "test" # main, test, dev
      CONFIG: "/opt/ripple/etc/rippled-test.cfg"
      #    volumes:
    #   - ./rippled_docker/cfg:/opt/ripple/etc
    #   - ./data/rippled/var/lib:/var/lib/rippled
    #   - ./data/rippled/var/log:/var/log/rippled
    networks:
     clio-net:
       ipv4_address: 10.0.0.3

  db:
    container_name: cassandra
    image: cassandra:4.0.4
    # volumes:
    #   - ./data/cassandra:/var/lib/cassandra
    networks:
     clio-net:
       ipv4_address: 10.0.0.4

networks:
  clio-net:
    name: clio-net
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/16
         gateway: 10.0.0.1
