name: Build Clio
on:
  push:
    branches:  [master, release, develop, develop-next]
  pull_request:
    branches:  [master, release, develop, develop-next]
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Get source
        uses: actions/checkout@v3

      - name: Run clang-format
        uses: XRPLF/clio-gha/lint@main

  build_clio:
    name: Build Clio
    needs: lint
    runs-on: [self-hosted, Linux]
    steps:

      - name: Clone Clio repo
        uses: actions/checkout@v3
        with:
          path: clio_src

      - name: Clone Clio CI repo
        uses: actions/checkout@v3
        with:
          path: clio_ci
          repository: 'XRPLF/clio-ci'

      - name: Build
        uses: XRPLF/clio-gha/build@main

      - name: Artifact packages
        uses: actions/upload-artifact@v3
        with:
          name: clio_packages
          path: ${{ github.workspace }}/*.deb

      - name: Artifact clio_tests
        uses: actions/upload-artifact@v3
        with:
          name: clio_tests
          path: clio_tests

  test_clio:
    name: Test Clio
    runs-on: [self-hosted, Linux]
    needs: build_clio
    steps:
      - name: Get clio_tests artifact
        uses: actions/download-artifact@v3
        with:
          name: clio_tests

      - name: Run tests
        uses: XRPLF/clio-gha/test@main
