name: build our image

on:
  push:
    branches: [multi-arch-image]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKERHUB_PW }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin
      - name: build the image
        run: |
          cd docker-multiarch
          docker buildx build --push \
            --tag legleux/multiarch-example:now \
            --platform linux/amd64,linux/arm64 .
