name: Publish Docker images

on:
  workflow_call:

jobs:
  deploy_images:
    name: Deploy Docker images
    runs-on: [self-hosted, Linux]
    steps:
      - name: Get tag
        id: tag_name
        run: |
          echo "::set-output name=DOCKER_REPO::rippleci"
          SHA=${GITHUB_SHA::7}
          echo "::set-output name=SHA_SHORT::${SHA}"
          echo "::set-output name=BRANCH::${{ github.event.release.target_commitish}}" # this for on release
          TAGNAME=clio:${SHA}
          echo "::set-output name=TAGNAME::${TAGNAME}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Test image
        run: |
          docker build . -f Dockerfile.test -t ${DOCKER_REPO}/${{ github.event.repository.name }}
          docker tag ${DOCKER_REPO}/${{ github.event.repository.name }} ${DOCKER_REPO}/${{ github.event.repository.name }}:${{ steps.tag_name.outputs.SHA_SHORT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PW }}

      - name: Push to Docker Hub
        run: |
          docker push ${DOCKER_REPO}/${{ github.event.repository.name }}

          docker tag ${DOCKER_REPO}/${{ github.event.repository.name }} ${DOCKER_REPO}/${{ github.event.repository.name }}:${{ steps.tag_name.outputs.BRANCH }}
          docker push ${DOCKER_REPO}/${{ github.event.repository.name }}:${{ steps.tag_name.outputs.BRANCH }}

          if [[ "${{ steps.tag_name.outputs.BRANCH }}" == "master" ]];then
            docker tag ${DOCKER_REPO}/${{ github.event.repository.name }}:${{ steps.tag_name.outputs.BRANCH }} ${DOCKER_REPO}/${{ github.event.repository.name }}:latest
            docker push ${DOCKER_REPO}/${{ github.event.repository.name }}:latest
          fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to ghcr
        run: |
          docker tag ${{ github.repository_owner }}/${{ github.event.repository.name }}   ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
