name: Deploy docker images on release
on:
  push:
    branches:  [master, release, develop, develop-next]
  pull_request:
    branches:  [master, release, develop, develop-next]
  workflow_dispatch:

env:
  TEST_TAG: testlegleux/clio:test

jobs:
  deploy_image:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     image: ["centos:7", "ubuntu:22.04"]
    name: Build clio in docker
    steps:

      - name: Get tag
        run: |
          TAGNAME=$(echo "clio" | tr : -)
          echo "::set-output name=TAGNAME::${TAGNAME}"
          sha=${GITHUB_SHA::7}
          echo "::set-output name=sha_short::${sha}"
          env
        id: tag_name

      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PW }}

      -
        name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          file: docker/Dockerfile
          build-args: |
              "IMAGE=clio"
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}-${{ steps.tag_name.outputs.sha_short }}
      -
        name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }}-${{ steps.tag_name.outputs.sha_short }}

      -
        name: Build and push
        uses: docker/build-push-action@v3
        if: ${{ github.event_name == 'push' }}
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: testlegleux/clio-${{ steps.tag_name.outputs.TAGNAME }}:${{ steps.tag_name.outputs.sha_short }}
