name: Deploy docker images on release
on:
  push:
    branches: [main, release, develop]
  pull_request:
    branches: [main, release, develop]

jobs:
  deploy_image:
    runs-on: [self-hosted, Linux]
    name: Build clio in docker
    steps:

      - name: Get tag
        id: tag_name
        run: |
          SHA=${GITHUB_SHA::7}
          echo "::set-output name=SHA_SHORT::${SHA}"
          BRANCH=${GITHUB_REF#refs/heads/}
          echo "::set-output name=BRANCH::${BRANCH}"
          TAGNAME=clio:${SHA}
          echo "::set-output name=TAGNAME::${TAGNAME}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: |
          docker build . -t testlegleux/"${{ steps.tag_name.outputs.TAGNAME }}"

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PW }}

      - name: Push to registry
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release' || github.ref == 'refs/heads/develop'
        run: |
          docker push testlegleux/${{ steps.tag_name.outputs.TAGNAME }}

          docker tag testlegleux/${{ steps.tag_name.outputs.TAGNAME }} testlegleux/clio:${{ steps.tag_name.outputs.BRANCH }}
          docker push testlegleux/clio:${{ steps.tag_name.outputs.BRANCH }}

          if [[ "${{ steps.tag_name.outputs.BRANCH }}" == "main" ]];then
            docker tag testlegleux/${{ steps.tag_name.outputs.TAGNAME }} testlegleux/clio:latest
            docker push testlegleux/clio:latest
          fi
